-- Generated by Oracle SQL Developer Data Modeler 21.4.1.349.1605
--   at:        2022-05-05 20:09:38 CST
--   site:      Oracle Database 21c
--   type:      Oracle Database 21c



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE asignacion (
    carnet  INTEGER NOT NULL,
    codigo  INTEGER NOT NULL,
    seccion VARCHAR2(2 CHAR) NOT NULL,
    ano     VARCHAR2(4 CHAR) NOT NULL,
    ciclo   VARCHAR2(50 CHAR) NOT NULL,
    zona    INTEGER,
    nota    INTEGER
);

ALTER TABLE asignacion
    ADD CONSTRAINT asignacion_pk PRIMARY KEY ( carnet,
                                               seccion,
                                               codigo,
                                               ano,
                                               ciclo );

CREATE TABLE carrera (
    carrera INTEGER NOT NULL,
    nombre  VARCHAR2(50 CHAR)
);

ALTER TABLE carrera ADD CONSTRAINT carrera_pk PRIMARY KEY ( carrera );

CREATE TABLE catedratico (
    cat           INTEGER NOT NULL,
    nombre        VARCHAR2(50 CHAR),
    sueldomensual NUMBER
);

ALTER TABLE catedratico ADD CONSTRAINT catedratico_pk PRIMARY KEY ( cat );

CREATE TABLE curso (
    codigo INTEGER NOT NULL,
    nombre VARCHAR2(50 CHAR)
);

ALTER TABLE curso ADD CONSTRAINT curso_pk PRIMARY KEY ( codigo );

CREATE TABLE dia (
    dia    INTEGER NOT NULL,
    nombre VARCHAR2(50 CHAR)
);

ALTER TABLE dia ADD CONSTRAINT dia_pk PRIMARY KEY ( dia );

CREATE TABLE estudiante (
    carnet          INTEGER NOT NULL,
    nombre          VARCHAR2(50 CHAR),
    ingresofamiliar NUMBER,
    fechanacimiento DATE
);

ALTER TABLE estudiante ADD CONSTRAINT estudiante_pk PRIMARY KEY ( carnet );

CREATE TABLE horario (
    codigo   INTEGER NOT NULL,
    seccion  VARCHAR2(2 CHAR) NOT NULL,
    ano      VARCHAR2(4 CHAR) NOT NULL,
    ciclo    VARCHAR2(50 CHAR) NOT NULL,
    periodo  INTEGER NOT NULL,
    dia      INTEGER NOT NULL,
    edificio VARCHAR2(10 CHAR) NOT NULL,
    salon    VARCHAR2(10 CHAR) NOT NULL
);

ALTER TABLE horario
    ADD CONSTRAINT horario_pk PRIMARY KEY ( seccion,
                                            ano,
                                            codigo,
                                            ciclo,
                                            dia,
                                            periodo );

CREATE TABLE inscrito (
    carrera          INTEGER NOT NULL,
    carnet           INTEGER NOT NULL,
    fechainscripcion DATE
);

ALTER TABLE inscrito ADD CONSTRAINT inscrito_pk PRIMARY KEY ( carrera,
                                                              carnet );

CREATE TABLE pensum (
    codigo         INTEGER NOT NULL,
    plan           VARCHAR2(10 CHAR) NOT NULL,
    carrera        INTEGER NOT NULL,
    obligatoriedad CHAR(1 CHAR),
    numcreditos    INTEGER,
    notaaprobacion INTEGER,
    zonaminima     INTEGER,
    credprerreq    INTEGER
);

ALTER TABLE pensum
    ADD CONSTRAINT pensum_pk PRIMARY KEY ( plan,
                                           carrera,
                                           codigo );

CREATE TABLE periodo (
    periodo    INTEGER NOT NULL,
    horainicio DATE,
    horafinal  DATE
);

ALTER TABLE periodo ADD CONSTRAINT periodo_pk PRIMARY KEY ( periodo );

CREATE TABLE plan (
    plan              VARCHAR2(10 CHAR) NOT NULL,
    carrera           INTEGER NOT NULL,
    nombre            VARCHAR2(50 CHAR),
    anoinicial        VARCHAR2(4 CHAR),
    cicloinicial      VARCHAR2(50 CHAR),
    anofinal          VARCHAR2(4 CHAR),
    ciclofinal        VARCHAR2(50 CHAR),
    numcreditoscierre INTEGER
);

ALTER TABLE plan ADD CONSTRAINT plan_pk PRIMARY KEY ( plan,
                                                      carrera );

CREATE TABLE prerreq (
    carrera INTEGER NOT NULL,
    plan    VARCHAR2(10 CHAR) NOT NULL,
    codigo  INTEGER NOT NULL,
    prerreq INTEGER NOT NULL
);

ALTER TABLE prerreq
    ADD CONSTRAINT prerreq_pk PRIMARY KEY ( plan,
                                            carrera,
                                            codigo,
                                            prerreq );

CREATE TABLE salon (
    edificio  VARCHAR2(10 CHAR) NOT NULL,
    salon     VARCHAR2(10 CHAR) NOT NULL,
    capacidad INTEGER
);

ALTER TABLE salon ADD CONSTRAINT salon_pk PRIMARY KEY ( edificio,
                                                        salon );

CREATE TABLE seccion (
    seccion         VARCHAR2(2 CHAR) NOT NULL,
    ano             VARCHAR2(4 CHAR) NOT NULL,
    ciclo           VARCHAR2(50 CHAR) NOT NULL,
    codigo          INTEGER NOT NULL,
    catedratico_cat INTEGER NOT NULL
);

ALTER TABLE seccion
    ADD CONSTRAINT seccion_pk PRIMARY KEY ( seccion,
                                            ano,
                                            codigo,
                                            ciclo );

ALTER TABLE asignacion
    ADD CONSTRAINT asignacion_estudiante_fk FOREIGN KEY ( carnet )
        REFERENCES estudiante ( carnet );

ALTER TABLE asignacion
    ADD CONSTRAINT asignacion_seccion_fk FOREIGN KEY ( seccion,
                                                       ano,
                                                       codigo,
                                                       ciclo )
        REFERENCES seccion ( seccion,
                             ano,
                             codigo,
                             ciclo );

ALTER TABLE horario
    ADD CONSTRAINT horario_dia_fk FOREIGN KEY ( dia )
        REFERENCES dia ( dia );

ALTER TABLE horario
    ADD CONSTRAINT horario_periodo_fk FOREIGN KEY ( periodo )
        REFERENCES periodo ( periodo );

ALTER TABLE horario
    ADD CONSTRAINT horario_salon_fk FOREIGN KEY ( edificio,
                                                  salon )
        REFERENCES salon ( edificio,
                           salon );

ALTER TABLE horario
    ADD CONSTRAINT horario_seccion_fk FOREIGN KEY ( seccion,
                                                    ano,
                                                    codigo,
                                                    ciclo )
        REFERENCES seccion ( seccion,
                             ano,
                             codigo,
                             ciclo );

ALTER TABLE inscrito
    ADD CONSTRAINT inscrito_carrera_fk FOREIGN KEY ( carrera )
        REFERENCES carrera ( carrera );

ALTER TABLE inscrito
    ADD CONSTRAINT inscrito_estudiante_fk FOREIGN KEY ( carnet )
        REFERENCES estudiante ( carnet );

ALTER TABLE pensum
    ADD CONSTRAINT pensum_curso_fk FOREIGN KEY ( codigo )
        REFERENCES curso ( codigo );

ALTER TABLE pensum
    ADD CONSTRAINT pensum_plan_fk FOREIGN KEY ( plan,
                                                carrera )
        REFERENCES plan ( plan,
                          carrera );

ALTER TABLE plan
    ADD CONSTRAINT plan_carrera_fk FOREIGN KEY ( carrera )
        REFERENCES carrera ( carrera );

ALTER TABLE prerreq
    ADD CONSTRAINT prerreq_curso_fk FOREIGN KEY ( prerreq )
        REFERENCES curso ( codigo );

ALTER TABLE prerreq
    ADD CONSTRAINT prerreq_pensum_fk FOREIGN KEY ( plan,
                                                   carrera,
                                                   codigo )
        REFERENCES pensum ( plan,
                            carrera,
                            codigo );

ALTER TABLE seccion
    ADD CONSTRAINT seccion_catedratico_fk FOREIGN KEY ( catedratico_cat )
        REFERENCES catedratico ( cat );

ALTER TABLE seccion
    ADD CONSTRAINT seccion_curso_fk FOREIGN KEY ( codigo )
        REFERENCES curso ( codigo );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            14
-- CREATE INDEX                             0
-- ALTER TABLE                             29
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
